gpus: -1 # -1 : use all gpus
save_dir: './saved' # dir for saving log, weights
workers: 4 # number of workers to generate data
model : 'plCosine'
dataset_name : 'natural_images'
batch_size: 16
epochs: 6

save_freq: 5

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  nesterov: true
  momentum: 0.9
  weight_decay: 1e-5
trainer_options:
  check_val_every_n_epoch: 1